-- =============================================================================
-- HỆ THỐNG QUẢN LÝ KHÁCH SẠN (HOTEL POS & MANAGEMENT SYSTEM)
-- DATABASE SCHEMA CHUẨN POSTGRESQL / SUPABASE READY
-- Tác giả: vanhunz
-- =============================================================================

-- Kích hoạt extension pgcrypto (nếu cần UUID hoặc mã hóa)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- HÀM TRIGGER TỰ ĐỘNG CẬP NHẬT CỘT updated_at
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 1. BẢNG PHÒNG KHÁCH SẠN (rooms)
-- =============================================================================
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(20) UNIQUE NOT NULL,
    floor INT NOT NULL DEFAULT 1,
    room_type VARCHAR(50) NOT NULL DEFAULT 'Phòng Đơn',
    is_double_room BOOLEAN NOT NULL DEFAULT FALSE,
    hourly_rate_base NUMERIC(12, 2) NOT NULL DEFAULT 80000,
    hourly_rate_extra NUMERIC(12, 2) NOT NULL DEFAULT 20000,
    overnight_single_rate NUMERIC(12, 2) NOT NULL DEFAULT 200000,
    overnight_double_rate NUMERIC(12, 2) NOT NULL DEFAULT 350000,
    daily_single_rate NUMERIC(12, 2) NOT NULL DEFAULT 350000,
    daily_double_rate NUMERIC(12, 2) NOT NULL DEFAULT 500000,
    status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'cleaning', 'maintenance')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER trigger_rooms_updated_at
    BEFORE UPDATE ON rooms
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 2. BẢNG PHIÊN THUÊ PHÒNG & HÓA ĐƠN (bookings)
-- =============================================================================
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
    room_number VARCHAR(20) NOT NULL,
    customer_name VARCHAR(150) DEFAULT 'Khách vãng lai',
    customer_phone VARCHAR(30),
    rental_type VARCHAR(20) NOT NULL DEFAULT 'hourly' CHECK (rental_type IN ('hourly', 'overnight', 'daily')),
    room_rate_mode VARCHAR(20) NOT NULL DEFAULT 'single' CHECK (room_rate_mode IN ('single', 'double')),
    expected_check_in TIMESTAMPTZ,
    check_in TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    check_out TIMESTAMPTZ,
    beer_qty INT NOT NULL DEFAULT 0,          -- 20.000đ/lon
    water_qty INT NOT NULL DEFAULT 0,         -- 10.000đ/chai
    soft_drink_qty INT NOT NULL DEFAULT 0,    -- 15.000đ/lon
    room_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    service_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    surcharge_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    surcharge_reason VARCHAR(255),
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    balance_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(20) DEFAULT 'cash' CHECK (payment_method IN ('cash', 'transfer', 'split')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled', 'reserved')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER trigger_bookings_updated_at
    BEFORE UPDATE ON bookings
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_bookings_room_number ON bookings(room_number);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_check_in ON bookings(check_in);
CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON bookings(created_at);

-- =============================================================================
-- 3. BẢNG PHIẾU CỌC GIỮ PHÒNG (reservations)
-- =============================================================================
CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
    room_number VARCHAR(20) DEFAULT '',
    customer_name VARCHAR(150) NOT NULL DEFAULT 'Khách đặt cọc',
    customer_phone VARCHAR(30),
    rental_type VARCHAR(20) NOT NULL DEFAULT 'daily' CHECK (rental_type IN ('hourly', 'overnight', 'daily')),
    expected_check_in TIMESTAMPTZ NOT NULL,
    deposit_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    deposit_method VARCHAR(20) NOT NULL DEFAULT 'transfer' CHECK (deposit_method IN ('transfer', 'cash')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'arrived', 'completed', 'cancelled')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER trigger_reservations_updated_at
    BEFORE UPDATE ON reservations
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status);
CREATE INDEX IF NOT EXISTS idx_reservations_expected_check_in ON reservations(expected_check_in);

-- =============================================================================
-- 4. BẢNG GIAO DỊCH DÒNG TIỀN / SỔ QUỸ PAYMENTS (payments)
-- =============================================================================
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
    reservation_id BIGINT REFERENCES reservations(id) ON DELETE SET NULL,
    room_number VARCHAR(20),
    payment_type VARCHAR(20) NOT NULL DEFAULT 'settlement' CHECK (payment_type IN ('advance', 'settlement', 'deposit', 'refund', 'expense')),
    method VARCHAR(20) NOT NULL DEFAULT 'cash' CHECK (method IN ('cash', 'transfer')),
    amount NUMERIC(12, 2) NOT NULL, -- Dương = Thu vào, Âm = Rút/Chi/Thối ra
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_payments_booking_id ON payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_reservation_id ON payments(reservation_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_type ON payments(payment_type);
CREATE INDEX IF NOT EXISTS idx_payments_method ON payments(method);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at);

-- =============================================================================
-- 5. BẢNG PHIẾU CHI QUỸ (expenses)
-- =============================================================================
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT 'Mua hàng / Nước uống',
    method VARCHAR(20) NOT NULL DEFAULT 'cash' CHECK (method IN ('cash', 'transfer')),
    requester VARCHAR(100) DEFAULT 'Lễ tân',
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    reject_reason VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER trigger_expenses_updated_at
    BEFORE UPDATE ON expenses
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_expenses_status ON expenses(status);
CREATE INDEX IF NOT EXISTS idx_expenses_created_at ON expenses(created_at);

-- =============================================================================
-- 6. BẢNG LỊCH SỬ CHỐT CA / KHÓA SỔ DÒNG TIỀN (shift_closures)
-- =============================================================================
CREATE TABLE IF NOT EXISTS shift_closures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closed_date DATE NOT NULL,
    shift_name VARCHAR(100) NOT NULL,
    net_cash NUMERIC(12, 2) NOT NULL DEFAULT 0,
    net_transfer NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_revenue_recognized NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cash_on_hand NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cash_difference NUMERIC(12, 2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by VARCHAR(100) DEFAULT 'Lễ tân'
);

CREATE INDEX IF NOT EXISTS idx_shift_closures_closed_date ON shift_closures(closed_date);

-- =============================================================================
-- 7. BẢNG NHẬT KÝ KIỂM TOÁN AUDIT LOG (audit_logs)
-- =============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(150) NOT NULL,
    details TEXT NOT NULL,
    user_name VARCHAR(100) NOT NULL DEFAULT 'Lễ tân',
    severity VARCHAR(20) DEFAULT 'info' CHECK (severity IN ('info', 'success', 'warning', 'danger')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

-- =============================================================================
-- 8. BẢNG CẤU HÌNH HỆ THỐNG & BẢO MẬT (system_configs)
-- =============================================================================
CREATE TABLE IF NOT EXISTS system_configs (
    config_key VARCHAR(50) PRIMARY KEY,
    config_value TEXT NOT NULL,
    description VARCHAR(255),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER trigger_system_configs_updated_at
    BEFORE UPDATE ON system_configs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- 9. BẢNG ĐỒNG BỘ BẢNG TÍNH EXCEL POS (excel_pos_rows)
-- =============================================================================
CREATE TABLE IF NOT EXISTS excel_pos_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
    row_date VARCHAR(20) NOT NULL,
    room_number VARCHAR(20),
    room_type VARCHAR(50),
    check_in VARCHAR(10),
    check_out VARCHAR(10),
    beer VARCHAR(20) DEFAULT '',
    filtered_water VARCHAR(20) DEFAULT '',
    soft_drink VARCHAR(20) DEFAULT '',
    water_amount NUMERIC(12, 2) DEFAULT 0,
    room_amount NUMERIC(12, 2) DEFAULT 0,
    extra NUMERIC(12, 2) DEFAULT 0,
    total_amount NUMERIC(12, 2) DEFAULT 0,
    payment_method VARCHAR(20) DEFAULT 'cash',
    note TEXT,
    status VARCHAR(20) DEFAULT 'Đang ở',
    is_date_separator BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_excel_pos_rows_date ON excel_pos_rows(row_date);

-- =============================================================================
-- BẬT ROW LEVEL SECURITY (RLS) CHO SUPABASE
-- =============================================================================
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_closures ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE excel_pos_rows ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách (Policies) cho phép truy cập đầy đủ (Anonymous & Authenticated)
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow full access on rooms" ON rooms;
    CREATE POLICY "Allow full access on rooms" ON rooms FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on bookings" ON bookings;
    CREATE POLICY "Allow full access on bookings" ON bookings FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on reservations" ON reservations;
    CREATE POLICY "Allow full access on reservations" ON reservations FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on payments" ON payments;
    CREATE POLICY "Allow full access on payments" ON payments FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on expenses" ON expenses;
    CREATE POLICY "Allow full access on expenses" ON expenses FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on shift_closures" ON shift_closures;
    CREATE POLICY "Allow full access on shift_closures" ON shift_closures FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on audit_logs" ON audit_logs;
    CREATE POLICY "Allow full access on audit_logs" ON audit_logs FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on system_configs" ON system_configs;
    CREATE POLICY "Allow full access on system_configs" ON system_configs FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Allow full access on excel_pos_rows" ON excel_pos_rows;
    CREATE POLICY "Allow full access on excel_pos_rows" ON excel_pos_rows FOR ALL USING (true) WITH CHECK (true);
END $$;

-- =============================================================================
-- THÊM BẢNG VÀO SUPABASE REALTIME (TỰ ĐỘNG ĐỒNG BỘ TỨC THÌ)
-- =============================================================================
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE rooms;
    ALTER PUBLICATION supabase_realtime ADD TABLE bookings;
    ALTER PUBLICATION supabase_realtime ADD TABLE reservations;
    ALTER PUBLICATION supabase_realtime ADD TABLE payments;
    ALTER PUBLICATION supabase_realtime ADD TABLE expenses;
    ALTER PUBLICATION supabase_realtime ADD TABLE shift_closures;
    ALTER PUBLICATION supabase_realtime ADD TABLE audit_logs;
    ALTER PUBLICATION supabase_realtime ADD TABLE system_configs;
    ALTER PUBLICATION supabase_realtime ADD TABLE excel_pos_rows;
EXCEPTION
    WHEN OTHERS THEN NULL; -- Bỏ qua nếu bảng đã tồn tại trong publication
END $$;

-- =============================================================================
-- KHỞI TẠO CẤU HÌNH & 11 PHÒNG SẴN SÀNG (KHÔNG CÓ DỮ LIỆU FAKE/MẪU)
-- =============================================================================

-- 1. Cấu hình hệ thống mặc định
INSERT INTO system_configs (config_key, config_value, description) VALUES
('staff_pin', '123', 'Mã PIN nhân viên lễ tân vào ca'),
('admin_password', '234', 'Mật khẩu quản trị viên Admin'),
('hotel_name', 'NHÀ NGHỈ THỦY TIÊN', 'Tên khách sạn / nhà nghỉ'),
('hotel_phone', '0905 123 456 - 0236 3888 999', 'Hotline lễ tân'),
('hotel_address', '123 Đường Trần Phú, Quận Hải Châu, TP. Đà Nẵng', 'Địa chỉ'),
('bank_name', 'MB Bank (Ngân hàng Quân Đội)', 'Ngân hàng nhận chuyển khoản'),
('bank_account', '0905123456', 'Số tài khoản nhận chuyển khoản'),
('bank_account_name', 'NHA NGHI THUY TIEN', 'Chủ tài khoản ngân hàng')
ON CONFLICT (config_key) DO UPDATE SET config_value = EXCLUDED.config_value;

-- 2. Khởi tạo 11 phòng thực tế (Tất cả đều sẵn sàng 'available', không có đơn ảo)
INSERT INTO rooms (room_number, floor, room_type, is_double_room, status) VALUES
('101', 1, 'Phòng Đơn', FALSE, 'available'),
('102', 1, 'Phòng Đơn', FALSE, 'available'),
('103', 1, 'Phòng Đơn', FALSE, 'available'),
('104', 1, 'Phòng Đơn', FALSE, 'available'),
('201', 2, 'Phòng Đơn', FALSE, 'available'),
('202', 2, 'Phòng Đơn', FALSE, 'available'),
('203', 2, 'Phòng Đơn', FALSE, 'available'),
('204', 2, 'Phòng Đơn', FALSE, 'available'),
('301', 3, 'Phòng Đơn', FALSE, 'available'),
('302', 3, 'Phòng Đơn', FALSE, 'available'),
('303', 3, 'Phòng Đơn', FALSE, 'available')
ON CONFLICT (room_number) DO UPDATE SET status = 'available';

-- =============================================================================
-- CÁC VIEW PHÂN TÍCH & BÁO CÁO DOANH THU (ANALYTICS VIEWS)
-- =============================================================================

-- View 1: Báo cáo dòng tiền theo ngày (Net Cash, Net Transfer, Tổng thực thu)
CREATE OR REPLACE VIEW view_daily_cashflow AS
SELECT 
    DATE(p.created_at) AS report_date,
    SUM(CASE WHEN p.method = 'cash' AND p.payment_type != 'expense' THEN p.amount ELSE 0 END) AS cash_inflow,
    SUM(CASE WHEN p.method = 'cash' AND p.amount < 0 THEN ABS(p.amount) ELSE 0 END) AS cash_outflow,
    SUM(CASE WHEN p.method = 'cash' THEN p.amount ELSE 0 END) AS net_cash,
    SUM(CASE WHEN p.method = 'transfer' THEN p.amount ELSE 0 END) AS net_transfer,
    SUM(p.amount) AS total_revenue_recognized,
    COUNT(p.id) AS total_transactions
FROM payments p
GROUP BY DATE(p.created_at)
ORDER BY report_date DESC;

-- View 2: Báo cáo tổng hợp tiêu thụ Minibar nước uống
CREATE OR REPLACE VIEW view_minibar_summary AS
SELECT 
    DATE(b.created_at) AS report_date,
    SUM(b.beer_qty) AS total_beer,
    SUM(b.water_qty) AS total_water,
    SUM(b.soft_drink_qty) AS total_soft_drink,
    SUM(b.beer_qty * 20000 + b.water_qty * 10000 + b.soft_drink_qty * 15000) AS total_minibar_revenue
FROM bookings b
GROUP BY DATE(b.created_at)
ORDER BY report_date DESC;

-- View 3: Danh sách phòng đang hoạt động (Active Bookings)
CREATE OR REPLACE VIEW view_active_rooms AS
SELECT 
    r.id AS room_id,
    r.room_number,
    r.floor,
    r.status AS room_status,
    b.id AS active_booking_id,
    b.customer_name,
    b.customer_phone,
    b.rental_type,
    b.check_in,
    b.paid_amount AS advance_paid
FROM rooms r
LEFT JOIN bookings b ON r.room_number = b.room_number AND b.status = 'active';
